services:
  web:
    env_file:
      - "docker/env/web"
      - "docker/env/web.local"
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        DEV_BUILD: "true"
    pull_policy: build
    image: djpg_sample-web:latest
    command: bash -c "/app/bin/release.sh && /app/bin/web.sh"
    volumes:
      - ${PWD}/docker/data/web:/data
      - ${PWD}:/app
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    env_file:
      - "docker/env/db"
      - "docker/env/db.local"
    user: "${UID:-1000}:${GID:-1000}"
    shm_size: "8g"
    image: "postgres:16-bookworm"
    command: -c "config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - ${PWD}/docker/data/db:/var/lib/postgresql/data
      - ${PWD}/docker/conf/db/postgresql.dev.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
